### ISSUE TITLE
Text Message

### ISSUE THREAD

**Issue by kurian86** [Ph3nol/NotificationPusher#10]
Hello again, I'm having another problem, is that I think the message text is not sent in Android notifications, I could not try on Ios.

In function getServiceMessageFromOrigin() just getting options and not text

**Comment by andycampbell92** [comment]
Hi I think this issue should be reopened as notifications on android appear to be blank again.

Can be fixed with the following:
$data['title'] = $message->getText();

Instead of:
$data['message'] = $message->getText()
