### ISSUE TITLE
Send push notification to Android, with laravel-push-notification, no response?

### ISSUE THREAD

**Issue by kenpeter** [Ph3nol/NotificationPusher#108]
A laravel-push-notification addon for laravel 5: https://github.com/davibennun/laravel-push-notification

In my routes.php, I have:
Route::get('/test_gcm', 'TestGCMController@index');

TestGCMController:

```
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Davibennun\LaravelPushNotification\Facades\PushNotification;

use App\Http\Requests;

class TestGCMController extends Controller
{
  public function index()
  {
    // Change it when device launching sometimes
    $deviceToken = "12345";

    $return = PushNotification::app('appNameAndroid')
      ->to($deviceToken)
      ->send('Hello World, i`m a push message');

    var_dump($return);
  }
}
```

so when I visit site.com/test_gcm, I did a var_dump, here is the result.

https://i.stack.imgur.com/4uLJZ.png

I am not sure it is successfully or failure. There is no indication in the image.

The android app is from this tutorial: http://www.androidhive.info/2016/02/android-push-notifications-using-gcm-php-mysql-realtime-chat-app-part-1/, I am able to get the GCM token, so the app is not working, but I don't receive any notification from the Android phone in emulator.

**Comment by ssboopathi1991** [comment]
@kenpeter 
i also get the same error. check the link
http://stackoverflow.com/questions/36518348/im-not-able-to-push-the-notification/36518485

**Comment by seyfer** [comment]
@kenpeter, is your issue solved with the help of the last answer?

**Comment by kenpeter** [comment]
@seyfer yes
