### ISSUE TITLE
Bundle does not work in Symfony 3

### ISSUE THREAD

**Issue by Ceslav** [Ph3nol/NotificationPusher#113]
Requirements incompatible with Symfony 3

symfony/options-resolver: ~2.3
symfony/console: ~2.3
symfony/process: ~2.3

**Comment by Ceslav** [comment]
???

**Comment by seyfer** [comment]
@Ceslav seems like it's updated
https://github.com/Ph3nol/NotificationPusher/commit/84928ed8b056d0b721d1ae4ebd2a36f7f38699b6

**Comment by Ceslav** [comment]
@seyfer yes, https://github.com/Ph3nol/NotificationPusher/pull/114 :)
