### ISSUE TITLE
how to get the response CODE from APNS server?

### ISSUE THREAD

**Issue by swansun95** [Ph3nol/NotificationPusher#115]
Hi

I'm trying to get the response Code from APNS server, to determine whether a PUSH action is successful or not. but i couldn't find a function or class to get such code. 

now, i can get the PushManager Object in the returning.

any hints or helps is appreciated.

Thanks

**Comment by swansun95** [comment]
updated

I figured it out by myself.

use the this code

`$adapter->getResponse()->getCode();`

**Comment by manik005** [comment]
hi @swansun95 , Does it returns exact response code for you?
