### ISSUE TITLE
How can i set time to live ?

### ISSUE THREAD

**Issue by pavanpatharde** [Ph3nol/NotificationPusher#116]
I am using laravel push notification which is based on your package.

I want to set the ttl . How can i set that ?
$push = PushNotification::app('appname'); $push->adapter->setAdapterParameters(['time_to_live' => 3]); $collection =$push->to($devices) ->send($gcm_message);

Is this the right way to do it ?

**Comment by pathardepavan** [comment]
@Ph3nol can you reply ?

**Comment by seyfer** [comment]
It was resolved in v2.2.16. 
https://github.com/Ph3nol/NotificationPusher/pull/127
