### ISSUE TITLE
iOS notification title

### ISSUE THREAD

**Issue by pabloleone** [Ph3nol/NotificationPusher#118]
I'm using Davibennun\LaravelPushNotification to send notifications to iOS devices and seems that the alert title could not be modified. But iOS documentation says that latest version allow title modification and I also see the title option added to the getServiceMessageFromOrigin function in Apns.php.

I used the following code to test:

``` php
\PushNotification::app('mDashIOS')
        ->to(\PushNotification::Device('xxxxx'))
        ->send(\PushNotification::Message('hello!', [
            'title' => 'testing'
        ]));
```

The package is installed using "sly/notification-pusher": "^2.2" that's currently 2.2.12 which I think is the latest version.

That piece of code works but the title still showing the app name. It doesn't respect the title argument.

Any idea on why this could be happening?

Thank you.

**Comment by seyfer** [comment]
@pabloleone is it solved?
