### ISSUE TITLE
Firebase support

### ISSUE THREAD

**Issue by jopereyral** [Ph3nol/NotificationPusher#122]
Actually Google drops [support for GCM](https://developers.google.com/cloud-messaging/) and now you can't create new projects for GCM.

So now the preferred way to send push notifications is using [Firebase](https://firebase.google.com/docs/cloud-messaging/) is there any approach for manage this change?

**Comment by marktopper** [comment]
Is there a reason this haven't been made yet?

**Comment by flaushi** [comment]
+1

**Comment by gvsrepins** [comment]
Is there any plans for a FCM adapter?

**Comment by flaushi** [comment]
I faced the same problem, but solved it by migrating to FCM completely. Honestly, FCM is even much more comfortable - however cannot work with any push service. Give it a try!

**Comment by Gameonn** [comment]
Is davibennun/laravel-push-notification ([https://packagist.org/packages/davibennun/laravel-push-notification]) not updated to handle firebase. How can we use FCM directly?

**Comment by jopereyral** [comment]
@Gameonn already is pretty straightforward using HTTP request to FCM servers https://firebase.google.com/docs/cloud-messaging/server. It would be nice to have some adapter for this service

**Comment by buryni** [comment]
+1

**Comment by turbo124** [comment]
#138 addresses this with a dedicated FCM Adapter. I am waiting for this pull request to be committed.

**Comment by seyfer** [comment]
FCM support added via https://github.com/Ph3nol/NotificationPusher/pull/141
