### ISSUE TITLE
GCM Adapter misspelled parameters leading to wrong behavior

### ISSUE THREAD

**Issue by theluk** [Ph3nol/NotificationPusher#126]
The GCM Adapter uses from line 125 until 129 camelCased parameter names but defines them in `getDefinedParameters` in snakeCase.

this results in Erros if you pass the params into construct in camelCase.
if you pass them as defined in snakeCase the ServiceMessage is constructed without those keys

**Comment by seyfer** [comment]
Connected issue https://github.com/Ph3nol/NotificationPusher/issues/81
