### ISSUE TITLE
push gsm sent messages not working

### ISSUE THREAD

**Issue by sadiaharel** [Ph3nol/NotificationPusher#130]
first i must to say thank for your library. 
it is very helpful!
i'm have devices with an verify token.
but when i;m tring to send message - He brings me an answer:
![image](https://cloud.githubusercontent.com/assets/22448418/19959090/ab88f27a-a1ac-11e6-98eb-9a9a14c9cada.png)
![image](https://cloud.githubusercontent.com/assets/22448418/19960577/57aef7f8-a1b6-11e6-93e8-9945510953b2.png)

**Comment by seyfer** [comment]
Check your API key.
