### ISSUE TITLE
Support for Android - FCM

### ISSUE THREAD

**Issue by bathan** [Ph3nol/NotificationPusher#132]
Hi! The zendframework/zendservice-google-gcm has already updated its code to support FCM. Could you update dependencies on your composer.json to support this?

**Comment by turbo124** [comment]
I've implemented FCM Adapter here: #138 just needs to be committed to master.

**Comment by jaystepin** [comment]
Hello,
Any plan to update composer for FCM support??

**Comment by seyfer** [comment]
@Ph3nol, a lot of people rely on this repo. Please, update it.

**Comment by turbo124** [comment]
@seyfer this project is abandoned, just fork and update as required....

**Comment by seyfer** [comment]
@turbo124 nope, the author just answered here https://github.com/Ph3nol/NotificationPusher/issues/150

We have hope. :) 
Probably I would try to maintain it, join if you want.

**Comment by seyfer** [comment]
@turbo124, I will check your pull as soon as possible (probably on weekends).

**Comment by seyfer** [comment]
Closed since Zend lib was updated in composer.json.
