### ISSUE TITLE
Class 'Sly\NotificationPusher\Adapter\' not found

### ISSUE THREAD

**Issue by cmarceloo** [Ph3nol/NotificationPusher#143]
When I try to send a notification the following error appear: 

**Class 'Sly\NotificationPusher\Adapter\' not found**

**Comment by seyfer** [comment]
@cmarceloo , could you please provide more information? 
What is your autoloading config? Do you use composer?

**Comment by anilkumar201241** [comment]
Hello can you provide me help. I getting the same issue

**Comment by seyfer** [comment]
@cmarceloo, @anilkumar201241 
I can't provide you any support if you will not add more information about your environment and configuration.
Do you use autoload in your project? Do you use [composer](https://getcomposer.org/download/)?

**Comment by mubassirhayat** [comment]
Check if you have provided the name of the adapter you want to use. Adapter is a namespace you have to select a class from it
