### ISSUE TITLE
rename ttl to time_to_live to use the function

### ISSUE THREAD

**Issue by sumeena** [Ph3nol/NotificationPusher#144]
https://github.com/Ph3nol/NotificationPusher/blob/master/src/Sly/NotificationPusher/Adapter/Gcm.php

getDefinedParameters are different from getServiceMessageFromOrigin used parameter.

rename ttl to time_to_live
rename collapseKey to  collapse_key
rename restrictedPackageName to restricted_package_name
rename delayWhileIdle to delay_while_idle
rename dryRun to dry_run

**Comment by seyfer** [comment]
Will check it soon https://github.com/Ph3nol/NotificationPusher/pull/145

**Comment by seyfer** [comment]
Related issue https://github.com/Ph3nol/NotificationPusher/issues/126

**Comment by seyfer** [comment]
Closed by #127
