### ISSUE TITLE
Question: How to detect invalid Android tokens?

### ISSUE THREAD

**Issue by AlexBa** [Ph3nol/NotificationPusher#147]
Hey,
I just have a small problem which is not very clear for me:
How do I detect invalid Android API tokens?

Do I just have to check the result of ```$pushManager->push()```?

Thank you very much in advance!

**Comment by seyfer** [comment]
+1 here

**Comment by seyfer** [comment]
@AlexBa please, check answer here https://github.com/Ph3nol/NotificationPusher/issues/135

It's the same, just get a response object, here you will find answers for all tokens which were sent.
You could use this answers in your business logic.

**Comment by seyfer** [comment]
It will be improved with an accomplishment of this issue: https://github.com/Ph3nol/NotificationPusher/issues/151

**Comment by seyfer** [comment]
Closed by https://github.com/Ph3nol/NotificationPusher/issues/151
See https://github.com/Ph3nol/NotificationPusher/blob/master/doc/facades.md
