### ISSUE TITLE
Seems this project dead, any good suggestion for an alternative?

### ISSUE THREAD

**Issue by kernio** [Ph3nol/NotificationPusher#150]
Look like this report is dead almost a year. Does anyone have some good, well-maintained alternatives?

**Comment by seyfer** [comment]
@Ph3nol, please add maintainers to the project.

**Comment by Ph3nol** [comment]
Hi everybody,
Sorry about that, I have no time to maintain this library...
I was thinking of creating a new version and maintaining that one, but still complicated to find time for that.

Anyone wants to be a maintainer before that? @seyfer?

**Comment by seyfer** [comment]
@Ph3nol, I could try on weekends. At least some pull requests could be merged.

Please, tell me more about new version also. Probably I could participate in development.
My skype: seyferseed

**Comment by Ph3nol** [comment]
Hey @seyfer,
Thank you so much for your time and your e-mail.
I'll answer it with some informations about new possible version.
Thank you again.
