### ISSUE TITLE
[Proposal] Add BaseResponse class

### ISSUE THREAD

**Issue by seyfer** [Ph3nol/NotificationPusher#151]
Now we have `BaseAdapter` with `response` field.
The problem is that for different adapters we have different response objects assigned to `response` field.

GCM - `ZendService\Google\Gcm\Response`
APNS - `ZendService\Apple\Apns\Response\Message`

And after that `BaseAdapter::getResponse()` returns one of this object.
Such approach breaks encapsulation and forces client code to take care of proper response processing.

I suggest adding `BaseResponse` object with implementations for each adapter.
`BaseResponse` would contain `originalResponse` field in which unique response for an adapter will be encapsulated.
And client code would interact only with `ResponseInterface` which will have the same structure and methods.

**Comment by Ph3nol** [comment]
I definitely agree.
Thanks for your suggestion. :)

**Comment by seyfer** [comment]
@Ph3nol, shall I start v2.3 for it or it shall be 3.0 because of interface change? Or 3.0 possibly would be a new version which you wanted to talk about?

**Comment by Ph3nol** [comment]
@seyfer, according to me, a v2.3 should be perfect for this.

**Comment by seyfer** [comment]
Closed in v2.3.0
