### ISSUE TITLE
How set "notification" param in GCM adapter

### ISSUE THREAD

**Issue by juratitov** [Ph3nol/NotificationPusher#153]
Hello! How I can setup for GCM Adapter this options
```
"notification" : {
      "body" : "great match!",
      "title" : "Portugal vs. Denmark",
      "icon" : "myicon"
    }
```

In \ZendService\Google\Gcm\Message isset method 

```
 /**
     * Set notification
     *
     * @param array $data
     * @return Message
     */
    public function setNotification(array $data)
    {
```

But in Sly\NotificationPusher\Adapter 

```
 /**
     * Get service message from origin.
     *
     * @param array $tokens Tokens
     * @param BaseOptionedModel|\Sly\NotificationPusher\Model\MessageInterface $message Message
     *
     * @return \ZendService\Google\Gcm\Message
     * @throws \ZendService\Google\Exception\InvalidArgumentException
     */
    public function getServiceMessageFromOrigin(array $tokens, BaseOptionedModel $message)
    {
        $data            = $message->getOptions();
        $data['message'] = $message->getText();

        $serviceMessage = new ServiceMessage();
        // IF I USE THAT, THAN CAN SEND DATA FROM $message->getOptions()
        // $serviceMessage->setNotification($data); // I ADDED IT!!!! HOW setNotification() call???
        $serviceMessage->setRegistrationIds($tokens);
        $serviceMessage->setData($data);
        $serviceMessage->setCollapseKey($this->getParameter('collapseKey'));
        $serviceMessage->setRestrictedPackageName($this->getParameter('restrictedPackageName'));
        $serviceMessage->setDelayWhileIdle($this->getParameter('delayWhileIdle', false));
        $serviceMessage->setTimeToLive($this->getParameter('ttl', 600));
        $serviceMessage->setDryRun($this->getParameter('dryRun', false));

        return $serviceMessage;
    }
```

**Comment by AlboVieira** [comment]
@juratitov to fix it I had to fork the project and add these lines:
```
$serviceMessage->addNotification('color', $data['color']);
$serviceMessage->addNotification('body', $data['body']); 
```
ZendGCM with FCM uses notification array instead of data.

**Comment by seyfer** [comment]
@AlboVieira , great, please make a pull request.

**Comment by asadijabar** [comment]
https://github.com/asadijabar/push-notification-library

**Comment by seyfer** [comment]
@AlboVieira merged.

**Comment by BrunoMessias** [comment]
After this merge, im getting a error when a recieve the data in android.

**Comment by seyfer** [comment]
@BrunoMessias , probably it's because android app trying to get notification data in the old data path, not in the notification, where it suppose to be. If you have access to Android app code - you need to fix it.
Otherwise stay with the previous version.

Only one way here to keep the backward compatibility is to copy notification data in the data and in the notification path. But in this case, more developers would still use the wrong place for getting data into their Android apps. It's not an option.

**Comment by seyfer** [comment]
@BrunoMessias , you were right.
This fixed back here https://github.com/Ph3nol/NotificationPusher/commit/a86b2be3aa2336ad03be5a5a7adb270144c7f003
