### ISSUE TITLE
Sending 'silent' notifications

### ISSUE THREAD

**Issue by pataar** [Ph3nol/NotificationPusher#159]
Hello,

I was wondering if it would be possible to send 'silent' notifications. So notifications that basically skip the  devices' notification center in both Android and iOS. Any idea how?

Thanks in advance!

**Comment by pataar** [comment]
Hi @bmourat, unfortunately not yet. Still waiting for a response.

**Comment by aliemam** [comment]
Hi
if by 'silent' you mean push notification which device wont handle (wont show any notif to user), it called dry run. you can set option dry run to true. it actually a feature by gcm for developers.

**Comment by bmourat** [comment]
@aliemam thanks!

**Comment by pataar** [comment]
@aliemam Thank you, I'm going try this soon.
