### ISSUE TITLE
Can't use with PHP 5.6?

### ISSUE THREAD

**Issue by dongmai** [Ph3nol/NotificationPusher#168]
Hi everyone, 

Sorry for my naive question, but It seems not working on PHP 5.6 as I'm getting an error: 

**Parse error**: syntax error, unexpected '?', expecting variable (T_VARIABLE) in **/Applications/XAMPP/xamppfiles/htdocs/nn-web/vendor/symfony/options-resolver/OptionsResolver.php** on line **980**

I know I have to upgrade PHP, that's ok on my local machine but not on the server since I've very limitation on it.

Any suggestion? Thanks!

**Comment by dongmai** [comment]
I downed it to v2.3.4 and it worked fine now.

**Comment by seyfer** [comment]
@dongmai I see the problem

current composer config set to php >= 5.6, so it could install Symfonye packages compatible with php7+
it could be changed to php <= 5.6. then it will be restricted. 
but then people with php7 would not be able to use the library. so you need to resolve such deps manually.
you can use 2.3.5 but in your project composer config, you need to set lower version for 
`symfony/options-resolver` or `symfony` packages.

**Comment by seyfer** [comment]
@dongmai try to just change in your project composer json
```
"config": {
        "platform": {
            "php": "5.3.5"
        }
    },
```

and in require section
```
"php": "^5.6",
```

or try different ways from docs
https://getcomposer.org/doc/articles/versions.md#caret-version-range-
