### ISSUE TITLE
Unable to send push anymore : APN Invalid Token

### ISSUE THREAD

**Issue by alchy58** [Ph3nol/NotificationPusher#170]
Hi,
First of all, thank you for the lib, very useful !

I have added NotificationPush on an app in may. I store the token on server side so I can send push notification.

All where functionnal and I receveid push at this moment so I moved on others features.

Today, I added Android push support who is working well.

My problem is that iOS notifications won't work anymore, APNS telling me that the token is invalid. The token seems to be correct. The APNS certificate is still valid until may 2019.

I tried to send a notification with NWPusher (https://github.com/noodlewerk/NWPusher) to test the token apart my server code. The token is rejected too.

I can't find others Apple modification on APNS since may away this one : https://www.engadget.com/2018/06/04/ios-12-grouped-notifications/

So I don't think that NotificationPusher can be the problem but I open this ticket to have your point of view. Do you have any idea of why the tokens are rejected without any modifications on the code since it was functionnal some weeks ago ?

Thanks a lot !

**Comment by seyfer** [comment]
@alchy58 There are could be rules for spamming prevention involved. 
That's why we have functionality in this library to get and clean invalid tokens. Why?
You need to avoid sending messages to invalid tokens as much as possible. Otherwise, your messages provider could be banned. Maybe that's your case?

**Comment by alchy58** [comment]
Hey @seyfer, thanks a lot for your reply.
The problem was that I updated the app id so the certificate gone useless, I generate a new one.
APNS is not really talkative about the issue...

By the way, what you are saying is interessant. Can you tell me more about your cleaning functionnality, actually I just remove obsolete token if push return code is 8.
