### ISSUE TITLE
notificationData is required for FCM

### ISSUE THREAD

**Issue by punknroll** [Ph3nol/NotificationPusher#181]
I just found out that 'notificatinData' is required for sending messages through FCM for android. Without that param the response shows no errors but messages don't come up in the android app.

`$params['notificationData'] = ['title' => 'this is my title', 'body' => 'this is my notification text'];`
`$message = new Message('This is an example.', $params);`

So I think the documentation here is misleading.

https://github.com/Ph3nol/NotificationPusher/blob/master/doc/gcm-fcm-adapter.md

**Comment by seyfer** [comment]
@punknroll could you please edit it and propose a PR?

**Comment by rossjcooper** [comment]
Thanks for highlighting this, I've been stuck for hours trying to work out why my notifications weren't being sent properly. The docs are definitely confusing around this.

**Comment by seyfer** [comment]
Closed by https://github.com/Ph3nol/NotificationPusher/commit/012183c89be0dbd154c81fb769606172d0931cb2
