### ISSUE TITLE
APNS token length check violates Apple Guides

### ISSUE THREAD

**Issue by v-vodyanov** [Ph3nol/NotificationPusher#185]
I've got "Sly\NotificationPusher\Exception\AdapterException" while processing one user notification, to my surprise his token was 96 characters length and Pusher check (https://github.com/Ph3nol/NotificationPusher/blob/master/src/Sly/NotificationPusher/Adapter/Apns.php#L270) didn't pass it though. I've googled the question (https://stackoverflow.com/questions/12452448/size-of-iphone-device-token) and it seems like Apple guides are quite clear about it (https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/APNSOverview.html#//apple_ref/doc/uid/TP40008194-CH8-SW14):

>  APNs device tokens are of variable length. Do not hard-code their size. 

I guess it should be fixed according to guides.

**Comment by seyfer** [comment]
closed by https://github.com/Ph3nol/NotificationPusher/pull/193
