### ISSUE TITLE
Facade documentation unclear/misleading

### ISSUE THREAD

**Issue by tbsmark86** [Ph3nol/NotificationPusher#186]
I find it rather surprising that the facade sends each message to every device instead of treating the input as a list of pairs.

I suggest that this is explicitly stated in the documentation. Or the code could be changed.

Also the response array is somewhat buggy: It only contains the last response for each token.

**Comment by seyfer** [comment]
@tbsmark86 please, propose a PR with contribution how you see it or how it should be.

**Comment by tbsmark86** [comment]
For my use case i've hacked the code.

Before doing any PR I would need to know what is the wanted way? The current code with clear documentation or a change in the code? Of course an API change could break other code :/

In addition i'am not firm with this PSR stuff so i can't really do a pull request.

**Comment by seyfer** [comment]
@tbsmark86 how did you hack the code for your use case?

**Comment by tbsmark86** [comment]
`
--- GcmPushService.php-orig     2019-04-05 11:30:59.979263566 +0200
+++ GcmPushService.php  2019-12-02 09:41:14.345779480 +0100
@@ -92,6 +92,7 @@
         // Then declare an adapter.
         $gcmAdapter = new GcmAdapter($adapterParams);
 
+       /*
         // Set the device(s) to push the notification to.
         $devices = new DeviceCollection([]);
 
@@ -99,7 +100,28 @@
         foreach ($tokens as $token) {
             $devices->add(new Device($token, $deviceParams));
         }
+       */
 
+       if(count($tokens) != count($notifications)) {
+            throw new \InvalidArgumentException('Tokens and Notifcations not equal');
+       }
+
+       // XXX change api
+       for($i=0; $i<count($tokens); $i++) {
+           $token = $tokens[$i];
+           $notificationText = $notifications[$i];
+
+           // Then, create the push skel.
+            $message = new Message($notificationText, $messageParams);
+           $device = new Device($token, $deviceParams);
+
+            // Finally, create and add the push to the manager, and push it!
+            $push = new Push($gcmAdapter, $device, $message);
+            $pushManager->add($push);
+       }
+
+
+       /*
         foreach ($notifications as $notificationText) {
             // Then, create the push skel.
             $message = new Message($notificationText, $messageParams);
@@ -108,6 +130,7 @@
             $push = new Push($gcmAdapter, $devices, $message);
             $pushManager->add($push);
         }
+       */
 
         // Returns a collection of notified devices
`

Patch for apns is the same

**Comment by seyfer** [comment]
@tbsmark86 PR for the documentation update will be merged for sure
for change in the code, I'm not sure, but having a separate PR for it would help to review and to have it in the history for future considerations.

**Comment by tbsmark86** [comment]
I think I finally understand where I've gone wrong. Was to blind to see later once the Bug appeared and my users where complaining about being bombed by messages :)
