### ISSUE TITLE
Is it possible to send multiple messages to multiple devices without closing the connection?

### ISSUE THREAD

**Issue by boosis** [Ph3nol/NotificationPusher#22]
I guess at the moment after each push, the connection is closed. Is it possible to implement some kind of batch functionality where the connection is only closed when all messages are sent?

**Comment by billmn** [comment]
Any news about this?

**Comment by MilesYM** [comment]
Up, I'm trying to send push notifications to large number of devices without success

**Comment by lvandyk** [comment]
Hi all, would this still be an issue if I use queues? I dispatching each job onto a laravel queue to send this push. Will apple block my jobs since they think its a ddos? My problem is each of my pushes are highly customised and can happen at any moment.

**Comment by lvandyk** [comment]
Anyone?
