### ISSUE TITLE
Is there any way to extract registration ids that are not registered?

### ISSUE THREAD

**Issue by RobbieElias** [Ph3nol/NotificationPusher#45]
After I push a message to a couple of registration IDs, there are some that have an Invalid Registration response from GCM. Is there any way I can extract the registration IDs that are not valid?

**Comment by seyfer** [comment]
@RobbieElias, have a look at the documentation.

```
//easily access list of successful and invalid tokens
$invalidTokens    = $pushNotificationService->getInvalidTokens();
$successfulTokens = $pushNotificationService->getSuccessfulTokens();
```

https://github.com/Ph3nol/NotificationPusher/blob/master/doc/facades.md
