### ISSUE TITLE
Maximum execution exceeds on APNS push, perhaps the ServiceClient is not closed.

### ISSUE THREAD

**Issue by tscheepers** [Ph3nol/NotificationPusher#46]
I'm having trouble pushing APNS messages to devices. The pushes do show up, almost instantly, on the device. However the request that processes the sending exceeds in execution time.

This is a problem because i'm using queues and the queue will think the task has failed since it got a 500 and will retry. 

I've inspected the code and perhaps this could have something to do with the `ServiceClient` object. https://github.com/Ph3nol/NotificationPusher/blob/master/src/Sly/NotificationPusher/Adapter/Apns.php#L59

Or maybe I'm just doing something wrong. I am using Google App Engine.

Here is my code.

``` php
...
    function __construct()
    {
        $environment = Config::get('push.apns.environment') == 'development' ? PushManager::ENVIRONMENT_DEV : PushManager::ENVIRONMENT_PROD;

        $this->pushManager = new PushManager($environment);

        $this->apnsAdapter = new ApnsAdapter([
            'certificate' => Config::get('push.apns.certificate'),
            'passPhrase' => Config::get('push.apns.passPhrase')
        ]);
    }

    /**
     * Handle the command
     *
     * @param SendApnsNotificationCommand $command
     * @return mixed
     */
    public function handle($command)
    {
        $devices = $this->deviceCollectionForRecipients($command->recipients);

        $message = new PushMessage($command->message, array(
            'badge' => '+1'
        ));

        Log::info('Sending push notification: "' . $command->message . '" to '. iterator_count($devices) .' device(s): ' . $this->stringForDeviceCollection($devices));

        $push = new Push($this->apnsAdapter, $devices, $message);
        $this->pushManager->add($push);
        $result = $this->pushManager->push();

        Log::info('Notifications sent');

        return $result;
    }
...
```

My log. The `Notifications sent` log message is never reached.

```
10:55:28.875 production.INFO: Executing Clickin\ApnsTokens\SendApnsNotificationCommand on queue. [] []
10:55:28.976 production.INFO: Sending push notification: "Xander: Testerdietest" to 1 device(s): "17a0eed527d2471e1fd95af92b5716aa5d1ea8bc6e52098c048bf412f3771d4c",  [] []
10:56:29.449 PHP Fatal error:  The request was aborted because it exceeded the maximum execution time. in /base/data/home/apps/s~clickin-c1/one.378213990390859398/vendor/laravel/framework/src/Illuminate/Exception/Handler.php on line 130
10:56:29.449 PHP Fatal error:  The request was aborted because it exceeded the maximum execution time. in /base/data/home/apps/s~clickin-c1/one.378213990390859398/vendor/laravel/framework/src/Illuminate/Exception/Handler.php on line 180
```

**Comment by JavierMartinz** [comment]
I have the same issue @tscheepers How did you solve it?

**Comment by tscheepers** [comment]
In the end I implemented an HTTP bridge to avoid the socket connection in
my PHP code. But it is a bit of a hack.

https://github.com/Label305/APNs-HTTP-Bridge-PHP

Op zaterdag 9 mei 2015 heeft Javier Martínez <notifications@github.com> het
volgende geschreven:

> I have the same issue @tscheepers <https://github.com/tscheepers> How did
> you solve it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Ph3nol/NotificationPusher/issues/46#issuecomment-100462161>
> .
>


-- 
*Thijs Scheepers*
Software Engineer, Co-founder

*Label305*
Rigtersbleek-Zandvoort 10-105
7521BE Enschede
The Netherlands

office +31(0)53 711 34 99
mail thijs@label305.com
www www.label305.com
kvk 57752451

**Comment by JavierMartinz** [comment]
Thanks @tscheepers, so you need a nodejs server permanently listening?
