### ISSUE TITLE
getFeedback() empty?

### ISSUE THREAD

**Issue by simplenotezy** [Ph3nol/NotificationPusher#52]
I did successfully send a push notification to my device in production mode. I wanted to check feedback data, if I uninstalled the app. Now I uninstalled it, and installed another push enabling app (as suggested to update the APNS feedback server).

Now when I send the push, it is successfully delivered, but I have not received any feedback. The `getFeedback()` is empty.

This is my code (simplified):

```
    $pushManager = new PushManager('prod');

    $push = new Push($the_adapter, new Device('my device token'), new Message('Some message', $options));
    $pushManager->add($push);
    $pushManager->push();

    exit(var_dump($pushManager->getFeedback($the_adapter))); // no feedback recieved
```

UPDATE:
Even trying this with an invalid token returns no feedback

**Comment by NaimishS** [comment]
I have the same issue ...

**Comment by leewillis77** [comment]
Me too - anything we can do to help debug this?

**Comment by scambier** [comment]
Same.

**Comment by accent-interactive** [comment]
Same here for APNS. 

`$pushManager->getFeedback($adapter)` always returns an empty array, no matter if you send to real or bogus device ID's.

If you use the APNS adapter, the feedback is collected by `ZendService\Apple\Apns\Client\Feedback`

According to Zend docs, the feedback service "simply returns an array of Feedback responses. All tokens provided in the feedback should not be sent to again; unless the device re-registers for push notification."
See http://framework.zend.com/manual/current/en/modules/zendservice.apple.apns.html#feedback-service

So, it seems like `$pushManager->getFeedback($adapter)` should return an array of device IDs *not* currently registered with your app. In other words, it should return my bogus device Ids.

Anything I can do to help debug this?

**Comment by Ph3nol** [comment]
Thanks for your feedbacks guys.
I currently have no time to fix it, but feel free to make a PR, I'll review and merge it ASAP!
Thanks!

**Comment by accent-interactive** [comment]
Ouch, me neither. 

One thing I did notice is that the sockets in use for ZendService\Apple\Apns\Client\Feedback and ZendService\Apple\Apns\Client\Message are using different socket resources. Could that be at tje core of the problem?

```
class ZendService\Apple\Apns\Client\Feedback#972 (3) {
  protected $uris =>
  array(2) {
    [0] =>
    string(42) "ssl://feedback.sandbox.push.apple.com:2196"
    [1] =>
    string(34) "ssl://feedback.push.apple.com:2196"
  }
  protected $isConnected =>
  bool(true)
  protected $socket =>
  resource(422) of type (stream)
}
```
```
class ZendService\Apple\Apns\Client\Message#985 (3) {
  protected $uris =>
  array(2) {
    [0] =>
    string(41) "ssl://gateway.sandbox.push.apple.com:2195"
    [1] =>
    string(33) "ssl://gateway.push.apple.com:2195"
  }
  protected $isConnected =>
  bool(true)
  protected $socket =>
  resource(416) of type (stream)
}
```

**Comment by ktnam** [comment]
I have the same issue ...

**Comment by accent-interactive** [comment]
Ok guys, figured it out. The feedback call works. 
* Install your app and add the device id to your list of devices.
* Do a push notification
* Now uninstall the app
* Now do another push notification. 

The device id for the uninstalled app will appear from $pushManager->getFeedback($apnsAdapter), in this format:

```
array (
 [yourdeviceid] => DateTime Object
   (
      [date] => 2015-07-14 09:14:57
        [timezone_type] => 1
        [timezone] => +02:00
    )
)
```

Note that there are many records of this not working in sandbox mode. You can test with production mode with an adhoc build, though.

**Comment by vestaxpdx** [comment]
Hi,
When trying to get feedback I just get a timeout error. Any ideas?

var_dump($pushManager->getFeedback($the_adapter))

The above waits for a while then spits out:

```stream_socket_client(): unable to connect to tls://feedback.push.apple.com:2196 (Connection timed out)
Fatal error: Uncaught exception 'ZendService\Apple\Exception\RuntimeException' with message 'Unable to connect: tls://feedback.push.apple.com:2196: 110 (Connection timed out)' in ../NotificationPusher/vendor/zendframework/zendservice-apple-apns/library/ZendService/Apple/Apns/Client/AbstractClient.php:105```

**Comment by philokezzar** [comment]
Hi,
any help for getFeedback() empty?

**Comment by atkaye** [comment]
In case you guys didn't know this already `$pushManager->getFeedback($adaptor)` will only return the invalid tokens which were sent to since you last requested feedback.

Example:
1. (Send a push notification to 1000 users)
2. `$pushManager->getFeedback($adaptor); // Returns some tokens`
3. `$pushManager->getFeedback($adaptor); // Returns no tokens because nothing was sent since we last asked the question`

However, seemingly you can attempt to send an empty push notification (not visible to the user) which would appear in `$pushManager->getFeedback($adaptor);` if it was invalid. Therefore, in a roundabout way you can validate a token by sending a silent notification then requesting feedback afterwards.

That's the case for APNS anyway.

**Comment by seyfer** [comment]
@accentinteractive and @atkaye thank you for giving answers with explanation how apns feedback works for others.

@vestaxpdx, your requirement to send 70k+ tokens out of the scope of this library. You need to write some custom code and split your tokens into chunks.

**Comment by vestaxpdx** [comment]
Wow blast from the past! Yes I now use onesignal.com
