### ISSUE TITLE
Failed to enable crypto (Laravel + hhvm)

### ISSUE THREAD

**Issue by bradbernard** [Ph3nol/NotificationPusher#57]
When I run simple code to do a push notification via iOS I get this error: 
```
ErrorException in AbstractClient.php line 102:
Failed to enable crypto
```

Push.php:
```php
PushNotification::app('test')->to($deviceToken)->send('test')
```

Settings.php:
```php
return array(
    'test' => array(
        'environment' => 'development',
        'certificate' => base_path() . '/cert.pem',
        'passPhrase'  => env('CERT_PASS'),
        'service'     => 'apns'
    )
);
```

I am running this on Laravel Forge with hhvm installed. I think the problem is https://github.com/facebook/hhvm/issues/1647 but I am not too sure. 

The error says its here:
```
at stream_socket_client('ssl://gateway.sandbox.push.apple.com:2195', '0', '', '60', '4', resource) in AbstractClient.php line 102
```

**Comment by ShindeSatish** [comment]
I am getting the same issue any update on this??

**Comment by wrik** [comment]
https://github.com/facebook/hhvm/issues/1647

**Comment by LiangJianle** [comment]
i have the same question. It works when i shutdown the hhvm ...

When the problem solve then active hhvm again..

**Comment by bradbernard** [comment]
Closed in reference to HHVM fixing: https://github.com/facebook/hhvm/issues/1647
