### ISSUE TITLE
Logging capabilities

### ISSUE THREAD

**Issue by ShurikAg** [Ph3nol/NotificationPusher#58]
Hi, 

Is there an easy way to wire in logging (monolog or similar)?

Thanks,

**Comment by ShurikAg** [comment]
Anything about this?

**Comment by seyfer** [comment]
@ShurikAg, on my opinion logging, is out of the library scope.
Usually, you need to decouple your code as much as possible. So, it's a good idea to use different solutions for pushing notifications and for logging and connect them together in your specific app code.
