### ISSUE TITLE
APN not delivered when pushed to 100 ios devices, but it did work when sending to 2 devices

### ISSUE THREAD

**Issue by ktnam** [Ph3nol/NotificationPusher#61]
$push_devices[] = new Device($device_token, array('badge' => 0));
$devices = new DeviceCollection($push_devices);

**Comment by MilesYM** [comment]
Is it still the case ?

**Comment by ktnam** [comment]
yes, still the same.

**Comment by nbonamy** [comment]
Any updates? Not sure yet but seeing strange things...

**Comment by ktnam** [comment]
Noticed undelivered APN due to the invalid device token.
When pushed to many devices which include production and development tokens, APN sent without error but undelivered.

**Comment by markmooibroek** [comment]
I have the same issue. No error from APNS but no notifications are being send.

**Comment by marktopper** [comment]
I had same issue but it worked when upgrading the Zend framework from 1.1.1 to 1.2.0.

However, then it started telling me that some tokens where invalid.

**Comment by Flitskikker** [comment]
Were you able to fix this? @ktnam @markmooibroek @marktopper 
Maybe related to #136.

**Comment by seyfer** [comment]
Fixed in #155
