### ISSUE TITLE
How can I implement this NotificationPusher ?

### ISSUE THREAD

**Issue by ezekel** [Ph3nol/NotificationPusher#63]
Hi, can I ask how can I implement this NotificationPusher, Is there running example for this so that I can see in action or video tutorial for this.

Thank you in advance.

**Comment by petr-inmite** [comment]
Hello, I believe the docs published at Github are more than sufficient to get things up and running:

https://github.com/Ph3nol/NotificationPusher/blob/master/doc/getting-started.md
