### ISSUE TITLE
Gsm token validation

### ISSUE THREAD

**Issue by alexk984** [Ph3nol/NotificationPusher#64]
In my case gcm token includes ":" (colon symbol) and I have error  Adapter Gcm does not support ... token's device. I think regular expression should be changed

```
public function supports($token)
{
    return (bool) preg_match('/^[0-9a-zA-Z\-\_]+$/i', $token);
}
```

**Comment by akimapilot** [comment]
Google's documentation says that device's token could be any string with length up to 4096 symbols. So I strongly recommend to hardcode "return true;" or something like "return isset($token) && $token!='';"
I spent 2 hours trying to find the origin of the failure during sending messages. So believe me this changes should be applied asap.
Regards.

**Comment by Ph3nol** [comment]
Hey guys, thanks for this feedback. Feel free to open a PR, I'll merge it.
Thanks!

**Comment by centerorbit** [comment]
Done! Thanks @Ph3nol

**Comment by Ph3nol** [comment]
Thank you Andrew, I've just answered your PR.
