### ISSUE TITLE
ios push freezes

### ISSUE THREAD

**Issue by leitom** [Ph3nol/NotificationPusher#70]
Hi,
i have a problem when sending push notifications via the ios adapter.
The notification i'm sending is received but the request never get's finished so that it freezes all other outgoing notifications in the same process.

I cant find any thing in the logs. I'm just wondering if any other is having a similar issue?

I'm using both gcm and ios adapter.

**Comment by kevcart3** [comment]
What version of PHP is the server you are issuing the commands from running? I had a similar issue and updating to PHP 5.6.10 resolved the issue. See issue below:

https://bugs.php.net/bug.php?id=69393

**Comment by leitom** [comment]
Thank you so much for responding, i will check that out! I think this is a valid statement!

**Comment by leitom** [comment]
It seems that updating php version does the trick!
