### ISSUE TITLE
Zend-Http Location error in symfony 1.4

### ISSUE THREAD

**Issue by vivekgs2007** [Ph3nol/NotificationPusher#74]
Hi,
It is working if I use has separate instance. When I integrate with my application which is built on symfony 1.4 it is giving fatal error.

PHP Fatal error:  Class 'Zend\Http\Header\AbstractLocation' not found in symfony/lib/vendor/NotificationPusher/vendor/zendframework/zend-http/src/Header/Location.php on line 18
PHP Fatal error:  Call to a member function evictAll() on a non-object in on a non-object in symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/vendor/doctrine/Doctrine/Connection.php on line 1239

This is the critical issue.

**Comment by seyfer** [comment]
@vivekgs2007, please check your autoload config. 
Please use composer and configure your autoloading properly.
