### ISSUE TITLE
Pushes not being received by some devices

### ISSUE THREAD

**Issue by marktopper** [Ph3nol/NotificationPusher#90]
Some people does not seems to get the pushes, even though that the status of the push model is `sent`.

Any ideas how to debug this to figure out the where the issue is?

NOTE: Most of the people not getting the push message seems to be on iOS.

**Comment by bwaaaaaa** [comment]
I think you need to enable the app settings, you should allow the notification of the app.

**Comment by markmooibroek** [comment]
Seems the same issue: https://github.com/Ph3nol/NotificationPusher/issues/61

**Comment by seyfer** [comment]
Fixed in #155
