### ISSUE TITLE
GCM for  IOS

### ISSUE THREAD

**Issue by luisalvarez** [Ph3nol/NotificationPusher#91]
GCM allow to send notification to ios devices but need to add notification key intead of data or just use both, theres is a way to extend the ZendService\Google\Gcm\Message and override the toJson method.
Or another walk around

**Comment by luisalvarez** [comment]
I think that if you can change  ZendService\Google\Gcm\Message toJson method to check if a notification property is set inside or outside of data resolve the problem

**Comment by moffa90** [comment]
I have the same issue, please how we can to add the key "notification" for IOS GCM. 

For IOS when you send a GCM message needs a notification key like this:

```
$notification = array(
        "title" => $title,
        "text" => $message,
        "vibrate" => 1,
        "badge" => 0,
        "sound" => "default"
    );

$GCMData = array(
        'registration_ids' => $ids,
        'notification' => $notification,
        'data'=> $customData
    );
```

**Comment by seyfer** [comment]
@luisalvarez , @moffa90 have you considered to use [APNS](https://github.com/Ph3nol/NotificationPusher/blob/master/doc/apns-adapter.md instead)?

**Comment by HornWilly** [comment]
@luisalvarez If you have last version 2.3.*, you can insert in message options your data notification for iOS:
```
$message = new Sly\NotificationPusher\Model\Message(
  'your_message_will_display_in_data', 
  ['notificationData' => $notification]
);
```

**Comment by seyfer** [comment]
It seems like closed by the answer above.
