### ISSUE TITLE
Adapter Apns does not support XXXX token's device

### ISSUE THREAD

**Issue by abhijeetnaik** [Ph3nol/NotificationPusher#93]
Hi,
I am trying to send push notification to iOS Device. certificate.pem file is correct. 
I have created a route to send out a notification to IOS device. But when i am trying to call the function, its throwing me: -
local.ERROR: exception 'Sly\NotificationPusher\Exception\AdapterException' with message 'Adapter Apns does not support XXXX token's device' in /private/var/www/pattypets/vendor/sly/notification-pusher/src/Sly/NotificationPusher/Model/Push.php:90

Please see:- Its working well and good in android.

**Comment by allanpichardo** [comment]
Are you sure that the token string is properly formatted?

**Comment by abhijeetnaik** [comment]
@allanpichardo Thanks  i got this issue fixed. I was not getting proper formatted string and there was also a certificate issue.
