### ISSUE TITLE
I have one Problem in Ph3nol/NotificationPusher in GCM for IOS.

### ISSUE THREAD

**Issue by piyushpatil027** [Ph3nol/NotificationPusher#97]
Hi,

Hope you are doing great.I have seen your on git hub related to GCM for ios. I can not create proper json for ios push notification.

Can you help me to create proper json for ios.

Please help me as soon as possible.

**Comment by seyfer** [comment]
@piyushpatil027, first of all, GCM isn't for iOS. 
iOS uses a different protocol called APNS. Please look here: 
https://github.com/Ph3nol/NotificationPusher/blob/master/doc/apns-adapter.md
