### ISSUE TITLE
how to get android device token ?

### ISSUE THREAD

**Issue by guns65** [Ph3nol/NotificationPusher#98]
hi all ! 
how can i get android device token ?
thanks :)

**Comment by theobouwman** [comment]
Where are the device tokens for?
Helps me a lot!

**Comment by seyfer** [comment]
@guns65 @theobouwman,
You need to implement some endpoint on the backend, like 
yourdomain.com/api/register-device

And you need to provide this endpoint URL to the mobile app developer. Add dev will use an endpoint to send new device token every time when the app will be installed. 
On the backend, you need to store received device tokens in DB (maybe associated with you users).

Only after that, all infrastructure would be ready for use of this library.

You need to implement some front-end push button or some backend cron (queue is better) command. This command will load all deviceTokens from you DB with your back-end logic filtration and will send push notifications.
